### PR TITLE
Add "Undo Last Move" button

### PR DESCRIPTION
**Pull request by eirrw**
Tracks all moves made via Lat/Lng position using an in-memory array. The undo button added to the game screen will pop the last move off the end of the array and return to that position. The button is hidden for no-move games, since it's effectively useless.

If I should have made an issue first, please let me know.

<details>
<summary>screenshot</summary>

image

</details>

### CODE REVIEW

**Comment by benlikescode** [comment]
Will take a look at this soon. Not a problem, but for the future would be nice to first create an issue or feel free to message me.

Guessing the motivation for this feature is to just move around quicker?

**Comment by benlikescode** [comment]
I have the ability to create a checkpoint on the TODO but I guess both these options could be useful to have

**Review by benlikescode — CHANGES_REQUESTED** [review]
Tested it out and it seems to work as expected. Left a few comments on mostly small code style changes. Feel free to make the changes or if you want I can make them after merging.

**Comment by eirrw** [comment]
> Guessing the motivation for this feature is to just move around quicker?

Yep, pretty much. I find that it especially comes in handy when Street View decides to jump off a bridge or from a highway onto a side road.

**Review by benlikescode — APPROVED** [review]

**Comment by benlikescode** [comment]
Yes, definitely a nice to have for when it pans off bridges! Thanks for taking this on.

**Pull request merged**
